import type { NextConfig } from "next";
import legacyRedirects from "./src/data/legacy-redirects.json";

const nextConfig: NextConfig = {
  poweredByHeader: false,

  images: {
    // Cloudflare Workers has no built-in Next image optimizer, so serve images
    // as-is. Article images are already pre-sized at generation time.
    unoptimized: true,
    // Allow next/image to serve SVG files generated by the article pipeline
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    // Allow article images pasted from Pexels (via the image-search tool).
    remotePatterns: [{ protocol: "https", hostname: "images.pexels.com" }],
  },

  async headers() {
    return [
      {
        // Cache public images — 30 days, stale-while-revalidate 1 day
        source: "/images/:path*",
        headers: [
          { key: "Cache-Control", value: "public, max-age=2592000, stale-while-revalidate=86400" },
        ],
      },
    ];
  },

  // 301 redirects from URLs of the previous tsevending.com site that were
  // indexed by Google / carry external backlinks, so existing rankings and
  // link equity carry over to the closest equivalent page on the new site.
  // legacyRedirects is generated from the Wayback Machine URL history via
  // scripts/generate-legacy-redirects.mjs.
  async redirects() {
    return [
      {
        // Canonicalize www → apex (avoid duplicate content; canonical tags
        // already point to the apex). Apex is the one indexed by Google.
        source: "/:path*",
        has: [{ type: "host", value: "www.tsevending.com" }],
        destination: "https://tsevending.com/:path*",
        permanent: true,
      },
      {
        source: "/en/:path*",
        destination: "/",
        permanent: true,
      },
      {
        source: "/giao-thong-thong-minh",
        destination: "/",
        permanent: true,
      },
      ...legacyRedirects,
    ];
  },
};

export default nextConfig;

// Enables the Cloudflare bindings (e.g. ASSETS) during `next dev`.
import { initOpenNextCloudflareForDev } from "@opennextjs/cloudflare";
initOpenNextCloudflareForDev();
