export interface Province {
  slug: string;
  name: string;
  region: "north" | "central" | "south";
  demandLevel: "high" | "medium" | "low";
  population: string;
  keyIndustries: string[];
  industrialZones: string[];
  notableAreas: string[];
  marketContext: string;
  lockerContext: string;
  deliveryNote: string;
  faqExtra?: { q: string; a: string };
}

export const PROVINCES: Province[] = [
  {
    slug: "ha-noi",
    name: "Hà Nội",
    region: "north",
    demandLevel: "high",
    population: "8,5 triệu",
    keyIndustries: ["công nghệ thông tin", "tài chính - ngân hàng", "thương mại - dịch vụ", "sản xuất công nghiệp"],
    industrialZones: ["KCN Thăng Long", "KCN Nội Bài", "KCN Sài Đồng", "KCN Quang Minh", "KCN Phú Nghĩa", "KCN Bắc Thường Tín"],
    notableAreas: ["Cầu Giấy", "Đống Đa", "Hoàn Kiếm", "Hai Bà Trưng", "Thanh Xuân", "Hoàng Mai", "Long Biên", "Nam Từ Liêm"],
    marketContext: "Hà Nội là thị trường máy bán hàng tự động lớn thứ hai Việt Nam với nhu cầu cao tại hệ thống tòa nhà văn phòng hạng A, khu đô thị mới (Vinhomes, Gamuda City, EcoPark) và hơn 20 khu công nghiệp. Lực lượng lao động tri thức đông đảo, thói quen tiêu dùng tiện lợi 24/7 ngày càng phổ biến, đặc biệt tại các quận nội thành và hành lang Nhật Tân – Nội Bài.",
    lockerContext: "Hà Nội có mật độ chung cư cao cấp ngày càng tăng, đặc biệt tại các khu đô thị vệ tinh như Hoà Lạc, Đan Phượng, Mê Linh. Nhu cầu tủ locker nhận hàng thương mại điện tử bùng nổ theo đà phát triển của Shopee, TikTok Shop, Lazada.",
    deliveryNote: "TSE Vending có đội kỹ thuật trực tiếp tại Hà Nội, lắp đặt trong 1–2 ngày làm việc.",
    faqExtra: { q: "TSE Vending có đại lý hoặc kho tại Hà Nội không?", a: "Có. TSE Vending có đội kỹ thuật và kho linh kiện tại Hà Nội, đảm bảo lắp đặt nhanh và bảo trì trong ngày tại hầu hết các quận nội thành và khu công nghiệp Hà Nội." },
  },
  {
    slug: "ho-chi-minh",
    name: "TP. Hồ Chí Minh",
    region: "south",
    demandLevel: "high",
    population: "9,3 triệu",
    keyIndustries: ["thương mại - dịch vụ", "công nghệ cao", "tài chính - ngân hàng", "logistics", "sản xuất"],
    industrialZones: ["KCX Tân Thuận", "KCX Linh Trung", "KCN Bình Chiểu", "KCN Tân Bình", "KCN Tân Tạo", "KCN Lê Minh Xuân", "KCN Hiệp Phước"],
    notableAreas: ["Quận 1", "Quận 3", "Bình Thạnh", "Gò Vấp", "Thủ Đức", "Bình Chánh", "Nhà Bè", "Hóc Môn"],
    marketContext: "TP. Hồ Chí Minh là thị trường máy bán hàng tự động lớn nhất Việt Nam. Với hơn 9 triệu dân, hàng nghìn tòa nhà văn phòng, trung tâm thương mại và khu chế xuất hoạt động 3 ca, nhu cầu giải pháp bán lẻ tự phục vụ 24/7 rất cao. TSE Vending xuất phát từ TP.HCM nên có mạng lưới đối tác và đội kỹ thuật dày đặc nhất tại đây.",
    lockerContext: "TP.HCM dẫn đầu cả nước về thương mại điện tử, với lượng đơn hàng giao cuối ngày lớn nhất. Tủ locker thông minh tại chung cư, tòa nhà văn phòng ở các quận trung tâm và Thủ Đức giúp giải quyết bài toán giao nhận hàng cho cư dân bận rộn.",
    deliveryNote: "Văn phòng chính TSE Vending tại TP.HCM — lắp đặt trong ngày, hỗ trợ kỹ thuật 24/7.",
    faqExtra: { q: "Máy bán hàng tự động tại TP.HCM đặt ở đâu hiệu quả nhất?", a: "Tại TP.HCM, vị trí hiệu quả nhất gồm: tòa nhà văn phòng khu CBD (Quận 1, 3), các khu chế xuất Tân Thuận và Linh Trung (ca làm việc 3 ca), chung cư cao tầng ở Thủ Đức và Bình Thạnh, bệnh viện lớn (Chợ Rẫy, Gia Định, FV) và sân bay Tân Sơn Nhất." },
  },
  {
    slug: "binh-duong",
    name: "Bình Dương",
    region: "south",
    demandLevel: "high",
    population: "2,6 triệu",
    keyIndustries: ["sản xuất công nghiệp", "điện tử", "gỗ - nội thất", "dệt may", "logistics"],
    industrialZones: ["KCN VSIP I", "KCN VSIP II", "KCN VSIP III", "KCN Mỹ Phước 1-4", "KCN Sóng Thần", "KCN Nam Tân Uyên", "KCN Bàu Bàng"],
    notableAreas: ["Thủ Dầu Một", "Thuận An", "Dĩ An", "Bến Cát", "Tân Uyên", "Bàu Bàng"],
    marketContext: "Bình Dương là thủ phủ công nghiệp lớn nhất miền Nam với hơn 30 khu công nghiệp, hơn 50.000 doanh nghiệp FDI. Lực lượng công nhân làm việc 3 ca tại các KCN VSIP và Mỹ Phước tạo ra nhu cầu máy bán hàng tự động cực lớn, đặc biệt vào ca đêm (22h–6h) khi các cửa hàng đóng cửa.",
    lockerContext: "Hàng triệu công nhân sống trong khu nhà trọ và chung cư mini tại Bình Dương có nhu cầu nhận hàng thương mại điện tử linh hoạt. Tủ locker thông minh đặt tại khu nhà trọ, ký túc xá công nhân là giải pháp tối ưu.",
    deliveryNote: "TSE Vending có kỹ thuật viên và kho phụ tùng tại Bình Dương, phục vụ toàn bộ các KCN trong vòng 4 giờ.",
  },
  {
    slug: "dong-nai",
    name: "Đồng Nai",
    region: "south",
    demandLevel: "high",
    population: "3,3 triệu",
    keyIndustries: ["sản xuất công nghiệp", "điện tử - điện lạnh", "dệt may", "hóa chất", "chế biến thực phẩm"],
    industrialZones: ["KCN Long Thành", "KCN Nhơn Trạch 1-6", "KCN Amata Biên Hòa", "KCN Loteco", "KCN Giang Điền", "KCN Tam Phước"],
    notableAreas: ["Biên Hòa", "Long Thành", "Nhơn Trạch", "Trảng Bom", "Thống Nhất"],
    marketContext: "Đồng Nai là cửa ngõ kết nối TP.HCM với vùng Đông Nam Bộ, có trên 30 khu công nghiệp thu hút hàng trăm nghìn lao động. Nhu cầu máy bán hàng tự động tập trung mạnh tại các KCN Biên Hòa, Long Thành và Nhơn Trạch — nơi có nhiều nhà máy điện tử, may mặc vận hành liên tục 3 ca.",
    lockerContext: "Sân bay quốc tế Long Thành đang xây dựng sẽ kéo theo nhu cầu hạ tầng logistics và dịch vụ tiện ích lớn. Tủ locker tại khu nhà ở công nhân và khu đô thị mới gần sân bay là cơ hội đầu tư dài hạn.",
    deliveryNote: "Lắp đặt trong 1–2 ngày làm việc tại Đồng Nai. Kỹ thuật viên phục vụ từ TP.HCM và Bình Dương.",
  },
  {
    slug: "da-nang",
    name: "Đà Nẵng",
    region: "central",
    demandLevel: "high",
    population: "1,2 triệu",
    keyIndustries: ["du lịch - dịch vụ", "công nghệ thông tin", "cảng biển - logistics", "thương mại"],
    industrialZones: ["KCN Hòa Khánh", "KCN Hòa Cầm", "KCN An Đồn", "KCN Đà Nẵng", "KCN Liên Chiểu"],
    notableAreas: ["Hải Châu", "Ngũ Hành Sơn", "Sơn Trà", "Liên Chiểu", "Cẩm Lệ", "Hòa Vang"],
    marketContext: "Đà Nẵng là trung tâm du lịch và công nghệ hàng đầu miền Trung. Lượng du khách quốc tế đông đảo, mật độ khách sạn và resort cao, cùng với cộng đồng kỹ thuật số (IT park) phát triển mạnh tạo ra nhu cầu máy bán hàng tự động đa dạng: snack, nước uống, đồ tiện lợi tại các điểm du lịch và tòa nhà văn phòng IT.",
    lockerContext: "Nhu cầu giao nhận hàng trong ngành du lịch và thương mại điện tử tại Đà Nẵng tăng mạnh. Tủ locker tại chung cư và khu đô thị mới ven biển đang là giải pháp được nhiều ban quản lý quan tâm.",
    deliveryNote: "TSE Vending lắp đặt tại Đà Nẵng trong 2–3 ngày làm việc. Hỗ trợ kỹ thuật từ trung tâm khu vực miền Trung.",
  },
  {
    slug: "hai-phong",
    name: "Hải Phòng",
    region: "north",
    demandLevel: "high",
    population: "2,1 triệu",
    keyIndustries: ["cảng biển - logistics", "điện tử - thiết bị", "đóng tàu", "sản xuất công nghiệp"],
    industrialZones: ["KCN VSIP Hải Phòng", "KCN Deep C", "KCN Tràng Duệ", "KCN Đình Vũ", "KCN Nam Cầu Kiền", "KCN Nomura"],
    notableAreas: ["Hồng Bàng", "Ngô Quyền", "Lê Chân", "Dương Kinh", "Đình Vũ", "An Dương"],
    marketContext: "Hải Phòng là cửa ngõ xuất nhập khẩu phía Bắc với hệ thống cảng biển lớn nhất miền Bắc. Sự có mặt của LG, Dell, Bridgestone và hàng trăm nhà máy FDI tạo nhu cầu khổng lồ cho máy bán hàng tự động phục vụ công nhân ca đêm và nhân viên văn phòng.",
    lockerContext: "Khu đô thị mới ven biển và cảng logistics Hải Phòng có nhu cầu tủ locker thông minh cho giao nhận hàng hóa và bưu phẩm ngày càng tăng.",
    deliveryNote: "Lắp đặt tại Hải Phòng trong 1–2 ngày. Kỹ thuật viên từ đội Hà Nội và Hải Phòng phục vụ.",
  },
  {
    slug: "can-tho",
    name: "Cần Thơ",
    region: "south",
    demandLevel: "medium",
    population: "1,3 triệu",
    keyIndustries: ["nông nghiệp - chế biến thực phẩm", "thương mại - dịch vụ", "y tế - giáo dục", "logistics"],
    industrialZones: ["KCN Trà Nóc 1-2", "KCN Thốt Nốt", "KCN Cờ Đỏ", "KCN Ô Môn"],
    notableAreas: ["Ninh Kiều", "Bình Thủy", "Cái Răng", "Ô Môn", "Thốt Nốt"],
    marketContext: "Cần Thơ là trung tâm kinh tế, thương mại và y tế vùng Đồng bằng sông Cửu Long. Với hệ thống bệnh viện, trường đại học lớn (Đại học Cần Thơ, Đại học Y Dược) và chợ đầu mối nông sản sầm uất, nhu cầu máy bán hàng tự động tại bệnh viện, ký túc xá sinh viên và khu thương mại rất tiềm năng.",
    lockerContext: "Thương mại điện tử tăng trưởng nhanh tại Cần Thơ, nhu cầu tủ locker nhận hàng tại chung cư và khu dân cư mới đang hình thành.",
    deliveryNote: "Lắp đặt tại Cần Thơ trong 2–3 ngày làm việc. Hỗ trợ từ đội phía Nam.",
  },
  {
    slug: "khanh-hoa",
    name: "Khánh Hòa",
    region: "central",
    demandLevel: "medium",
    population: "1,3 triệu",
    keyIndustries: ["du lịch - dịch vụ", "thủy sản", "quốc phòng - công nghiệp"],
    industrialZones: ["KCN Suối Dầu", "KCN Ninh Thủy", "KCN Nam Cam Ranh"],
    notableAreas: ["Nha Trang", "Cam Ranh", "Cam Lâm", "Ninh Hòa", "Vân Phong"],
    marketContext: "Khánh Hòa – Nha Trang là điểm đến du lịch quốc tế nổi tiếng với lượng khách nước ngoài lớn. Nhu cầu máy bán hàng tự động tại khu resort, khách sạn 4–5 sao, casino và trung tâm hội nghị rất cao. Đặc biệt, khu kinh tế Vân Phong đang phát triển mạnh hứa hẹn nhu cầu lớn trong tương lai.",
    lockerContext: "Các khu resort và condotel tại Nha Trang có nhu cầu tủ locker thông minh cho lưu trữ hành lý và nhận hàng của khách lưu trú.",
    deliveryNote: "Lắp đặt tại Khánh Hòa trong 3–4 ngày làm việc. Hỗ trợ kỹ thuật từ đội miền Trung.",
  },
  {
    slug: "lam-dong",
    name: "Lâm Đồng",
    region: "central",
    demandLevel: "medium",
    population: "1,3 triệu",
    keyIndustries: ["du lịch - nghỉ dưỡng", "nông nghiệp công nghệ cao", "chế biến cà phê - chè"],
    industrialZones: ["KCN Phú Hội", "KCN Lộc Sơn"],
    notableAreas: ["Đà Lạt", "Bảo Lộc", "Di Linh", "Đơn Dương"],
    marketContext: "Đà Lạt là điểm du lịch nghỉ dưỡng nổi tiếng với lượng khách du lịch nội địa đông nhất Tây Nguyên. Nhu cầu máy bán hàng tự động tại khu du lịch, homestay, café và các tòa nhà thương mại trung tâm Đà Lạt đang tăng nhanh. Bảo Lộc với ngành chế biến trà-cà phê cũng có tiềm năng tại các nhà máy và khu công nghiệp.",
    lockerContext: "Homestay và khách sạn boutique tại Đà Lạt có nhu cầu tủ locker self-check-in và lưu trữ hành lý linh hoạt để phục vụ khách du lịch tự túc.",
    deliveryNote: "Lắp đặt tại Lâm Đồng trong 3–5 ngày làm việc. Giao thông Đà Lạt thuận tiện từ TP.HCM.",
  },
  {
    slug: "binh-dinh",
    name: "Bình Định",
    region: "central",
    demandLevel: "medium",
    population: "1,5 triệu",
    keyIndustries: ["cảng biển - logistics", "chế biến thủy sản", "gỗ - nội thất", "nông sản"],
    industrialZones: ["KCN Phú Tài", "KCN Long Mỹ", "KCN Nhơn Hội", "KCN Bình Nghi"],
    notableAreas: ["Quy Nhơn", "Phù Cát", "An Nhơn", "Tuy Phước"],
    marketContext: "Bình Định với cảng Quy Nhơn là trung tâm kinh tế miền Trung Nam. Sự phát triển của KKT Nhơn Hội và cảng biển quốc tế Quy Nhơn thu hút nhiều doanh nghiệp FDI, tạo nhu cầu máy bán hàng tự động tại các nhà máy và khu công nghiệp. Đại học Quy Nhơn và các trường cao đẳng tập trung đông sinh viên cũng là thị trường tiềm năng.",
    lockerContext: "Khu đô thị mới và chung cư tại TP. Quy Nhơn đang phát triển nhanh, nhu cầu tủ locker nhận hàng TMĐT tăng theo.",
    deliveryNote: "Lắp đặt tại Bình Định trong 3–4 ngày làm việc.",
  },
  {
    slug: "quang-nam",
    name: "Quảng Nam",
    region: "central",
    demandLevel: "medium",
    population: "1,5 triệu",
    keyIndustries: ["du lịch - dịch vụ", "sản xuất ô tô", "dệt may", "khai khoáng"],
    industrialZones: ["KCN Điện Nam - Điện Ngọc", "KCN Thuận Yên", "KCN Tam Hiệp", "KKT mở Chu Lai"],
    notableAreas: ["Tam Kỳ", "Hội An", "Điện Bàn", "Núi Thành", "Duy Xuyên"],
    marketContext: "Quảng Nam nổi tiếng với Hội An (UNESCO) và nhà máy ô tô THACO tại Chu Lai — khu kinh tế lớn nhất miền Trung. Nhu cầu máy bán hàng tự động tại nhà máy THACO và các nhà cung ứng vệ tinh, cùng với hàng nghìn nhân viên khách sạn tại Hội An - Đà Nẵng là cơ hội lớn.",
    lockerContext: "Hội An với lượng khách du lịch quốc tế đông đúc có nhu cầu tủ locker lưu trữ hành lý và nhận hàng cho khách du lịch.",
    deliveryNote: "Lắp đặt tại Quảng Nam trong 2–3 ngày (gần Đà Nẵng).",
  },
  {
    slug: "thua-thien-hue",
    name: "Thừa Thiên Huế",
    region: "central",
    demandLevel: "medium",
    population: "1,2 triệu",
    keyIndustries: ["du lịch - di sản", "giáo dục - y tế", "dệt may", "nông lâm sản"],
    industrialZones: ["KCN Phú Bài", "KCN La Sơn", "KCN Phong Điền"],
    notableAreas: ["Huế", "Hương Thủy", "Hương Trà", "Phú Lộc", "Phú Vang"],
    marketContext: "Huế là cố đô với mật độ trường đại học và sinh viên cao (Đại học Huế, Y Dược Huế). Nhu cầu máy bán hàng tự động tại ký túc xá, bệnh viện và khu du lịch di sản thế giới Huế đang tăng trưởng cùng với làn sóng đầu tư vào hạ tầng du lịch.",
    lockerContext: "Ký túc xá đại học và khu nhà trọ sinh viên tại Huế là thị trường tiềm năng cho tủ locker thông minh.",
    deliveryNote: "Lắp đặt tại Huế trong 2–3 ngày làm việc.",
  },
  {
    slug: "nghe-an",
    name: "Nghệ An",
    region: "central",
    demandLevel: "medium",
    population: "3,4 triệu",
    keyIndustries: ["nông lâm sản - chế biến", "sản xuất công nghiệp", "thương mại - dịch vụ"],
    industrialZones: ["KKT Đông Nam Nghệ An", "KCN Nam Cấm", "KCN Bắc Vinh", "KCN VSIP Nghệ An"],
    notableAreas: ["Vinh", "Cửa Lò", "Nghi Lộc", "Hưng Nguyên"],
    marketContext: "Nghệ An là tỉnh đông dân nhất Bắc Trung Bộ với KKT Đông Nam đang phát triển mạnh, thu hút dự án VSIP Nghệ An quy mô lớn. Trường Đại học Vinh và nhiều trường chuyên nghiệp tại thành phố Vinh tạo nhu cầu dài hạn cho máy bán hàng tự động tại ký túc xá và khu dân cư sinh viên.",
    lockerContext: "Với dân số đông và tốc độ đô thị hóa nhanh tại TP. Vinh, nhu cầu tủ locker thông minh tại chung cư và khu dân cư mới đang hình thành.",
    deliveryNote: "Lắp đặt tại Nghệ An trong 3–4 ngày làm việc.",
  },
  {
    slug: "thanh-hoa",
    name: "Thanh Hóa",
    region: "central",
    demandLevel: "medium",
    population: "3,7 triệu",
    keyIndustries: ["sản xuất công nghiệp", "lọc hóa dầu", "nông lâm thủy sản", "du lịch"],
    industrialZones: ["KKT Nghi Sơn", "KCN Lam Sơn - Sao Vàng", "KCN Bỉm Sơn", "KCN Hoàng Long"],
    notableAreas: ["TP. Thanh Hóa", "Sầm Sơn", "Bỉm Sơn", "Nghi Sơn"],
    marketContext: "Thanh Hóa có KKT Nghi Sơn với lọc hóa dầu Nghi Sơn và cảng biển nước sâu, thu hút hàng chục nghìn lao động công nghiệp. Nghỉ mát Sầm Sơn mỗi hè đón hàng triệu du khách tạo nhu cầu máy bán hàng tự động theo mùa rất lớn.",
    lockerContext: "Khu đô thị ven biển Sầm Sơn và các dự án công nhân viên chức tại Nghi Sơn là thị trường tiềm năng cho tủ locker.",
    deliveryNote: "Lắp đặt tại Thanh Hóa trong 3–4 ngày làm việc.",
  },
  {
    slug: "ha-tinh",
    name: "Hà Tĩnh",
    region: "central",
    demandLevel: "low",
    population: "1,3 triệu",
    keyIndustries: ["luyện kim - thép", "cảng biển", "nông nghiệp", "khai khoáng"],
    industrialZones: ["KKT Vũng Áng", "KCN Gia Lách", "KCN Phú Vinh"],
    notableAreas: ["TP. Hà Tĩnh", "Vũng Áng", "Kỳ Anh", "Hồng Lĩnh"],
    marketContext: "Hà Tĩnh có KKT Vũng Áng với Formosa Hà Tĩnh — tổ hợp thép lớn nhất Đông Nam Á, thu hút hàng chục nghìn lao động. Nhu cầu máy bán hàng tự động tập trung tại khu công nhân và nhà ăn ca đêm của các nhà máy lớn trong KKT.",
    lockerContext: "Khu ký túc xá công nhân Formosa và các dự án nhà ở xã hội tại Vũng Áng có nhu cầu tủ locker quản lý tài sản cá nhân.",
    deliveryNote: "Lắp đặt tại Hà Tĩnh trong 4–5 ngày làm việc.",
  },
  {
    slug: "quang-ninh",
    name: "Quảng Ninh",
    region: "north",
    demandLevel: "medium",
    population: "1,4 triệu",
    keyIndustries: ["du lịch - dịch vụ", "khai thác than", "cảng biển - logistics", "sản xuất công nghiệp"],
    industrialZones: ["KCN Cái Lân", "KCN Việt Hưng", "KCN Đông Mai", "KCN Hải Yên", "KKT Vân Đồn"],
    notableAreas: ["Hạ Long", "Móng Cái", "Cẩm Phả", "Uông Bí", "Vân Đồn"],
    marketContext: "Quảng Ninh với Vịnh Hạ Long (UNESCO) thu hút hàng triệu khách du lịch quốc tế mỗi năm. Sân bay Vân Đồn và KKT Vân Đồn đang phát triển nhanh. Nhu cầu máy bán hàng tự động tại khu du lịch, cảng tàu và khách sạn hạng sang ở Hạ Long rất lớn.",
    lockerContext: "Cảng tàu du lịch Hạ Long và các khu resort đảo Tuần Châu có nhu cầu tủ locker lưu trữ hành lý cho khách đi tàu.",
    deliveryNote: "Lắp đặt tại Quảng Ninh trong 2–3 ngày làm việc. Gần Hà Nội và Hải Phòng.",
  },
  {
    slug: "bac-ninh",
    name: "Bắc Ninh",
    region: "north",
    demandLevel: "high",
    population: "1,5 triệu",
    keyIndustries: ["điện tử - công nghệ cao", "sản xuất công nghiệp", "logistics"],
    industrialZones: ["KCN Yên Phong", "KCN Tiên Sơn", "KCN Quế Võ", "KCN VSIP Bắc Ninh", "KCN Đại Đồng - Hoàn Sơn"],
    notableAreas: ["TP. Bắc Ninh", "Từ Sơn", "Tiên Du", "Yên Phong", "Quế Võ"],
    marketContext: "Bắc Ninh là 'thủ đô điện tử' của Việt Nam — nơi đặt trụ sở Samsung Electronics Việt Nam (SEV, SEVT), Canon, LG và hàng trăm nhà cung ứng vệ tinh. Hàng trăm nghìn công nhân điện tử làm ca 3 tạo nhu cầu khổng lồ cho máy bán hàng tự động, đặc biệt các ca từ 22h–6h.",
    lockerContext: "Khu nhà ở công nhân và chung cư tập thể cho lao động Samsung tại Yên Phong là thị trường tủ locker thông minh lớn của miền Bắc.",
    deliveryNote: "Lắp đặt tại Bắc Ninh trong 1–2 ngày làm việc. Đội Hà Nội phục vụ trực tiếp.",
    faqExtra: { q: "Máy bán hàng tự động phục vụ ca đêm tại Bắc Ninh cần lưu ý gì?", a: "Với đặc thù ca đêm tại các nhà máy Samsung, LG ở Bắc Ninh, máy cần có hệ thống làm mát tốt, khả năng chứa nhiều loại sản phẩm (nước uống, thực phẩm, đồ dùng cá nhân) và kết nối IoT giám sát từ xa để đội vận hành tiếp hàng kịp thời. TSE Vending hỗ trợ cấu hình chuyên biệt cho môi trường nhà máy." },
  },
  {
    slug: "vinh-phuc",
    name: "Vĩnh Phúc",
    region: "north",
    demandLevel: "medium",
    population: "1,2 triệu",
    keyIndustries: ["sản xuất ô tô - xe máy", "điện tử", "chế biến thực phẩm"],
    industrialZones: ["KCN Khai Quang", "KCN Kim Hoa", "KCN Bình Xuyên", "KCN Thăng Long II"],
    notableAreas: ["Vĩnh Yên", "Phúc Yên", "Bình Xuyên", "Tam Đảo"],
    marketContext: "Vĩnh Phúc là tỉnh công nghiệp quan trọng phía Bắc với Toyota, Honda, Piaggio và nhiều tập đoàn Nhật Bản. Hàng chục nghìn công nhân chế tạo ô tô và xe máy tại các KCN Bình Xuyên và Khai Quang là thị trường mục tiêu cho máy bán hàng tự động.",
    lockerContext: "Khu nhà ở công nhân các nhà máy Nhật Bản tại Vĩnh Phúc có nhu cầu tủ locker theo chuẩn an toàn công nghiệp.",
    deliveryNote: "Lắp đặt tại Vĩnh Phúc trong 1–2 ngày làm việc từ Hà Nội.",
  },
  {
    slug: "hung-yen",
    name: "Hưng Yên",
    region: "north",
    demandLevel: "medium",
    population: "1,3 triệu",
    keyIndustries: ["điện tử - công nghệ", "cơ khí chế tạo", "chế biến thực phẩm"],
    industrialZones: ["KCN Thăng Long II", "KCN Phố Nối A", "KCN Minh Đức", "KCN Dệt may Phố Nối B"],
    notableAreas: ["Hưng Yên", "Văn Lâm", "Mỹ Hào", "Ân Thi"],
    marketContext: "Hưng Yên tiếp giáp Hà Nội và Bắc Ninh, là tỉnh công nghiệp với nhiều KCN điện tử và cơ khí đang mở rộng. Nhu cầu máy bán hàng tự động tăng theo tốc độ lấp đầy các khu công nghiệp mới trong hành lang kinh tế Bắc - Nam.",
    lockerContext: "Khu nhà ở xã hội cho công nhân tại Văn Lâm và Mỹ Hào đang phát triển, tạo nhu cầu tủ locker quản lý bưu phẩm.",
    deliveryNote: "Lắp đặt tại Hưng Yên trong 1–2 ngày làm việc từ Hà Nội.",
  },
  {
    slug: "hai-duong",
    name: "Hải Dương",
    region: "north",
    demandLevel: "medium",
    population: "1,9 triệu",
    keyIndustries: ["sản xuất công nghiệp", "chế biến thực phẩm", "điện tử", "may mặc"],
    industrialZones: ["KCN Đại An", "KCN Tân Trường", "KCN Phúc Điền", "KCN Nam Sách"],
    notableAreas: ["TP. Hải Dương", "Chí Linh", "Kinh Môn", "Cẩm Giàng"],
    marketContext: "Hải Dương là cầu nối giữa Hà Nội và Hải Phòng với nhiều khu công nghiệp sản xuất thực phẩm (Kinh Đô, Orion) và điện tử. Lực lượng lao động đông đảo trong ngành thực phẩm tạo nhu cầu đặc biệt cho máy bán hàng tự động tại dây chuyền sản xuất.",
    lockerContext: "Chung cư và khu nhà ở công nhân tại TP. Hải Dương đang phát triển nhanh, nhu cầu tủ locker đang hình thành.",
    deliveryNote: "Lắp đặt tại Hải Dương trong 1–2 ngày làm việc.",
  },
  {
    slug: "thai-nguyen",
    name: "Thái Nguyên",
    region: "north",
    demandLevel: "medium",
    population: "1,4 triệu",
    keyIndustries: ["điện tử - công nghệ cao (Samsung)", "luyện kim - thép", "giáo dục"],
    industrialZones: ["KCN Điềm Thụy", "KCN Yên Bình", "KCN Sông Công I-II", "KCN Quyết Thắng"],
    notableAreas: ["TP. Thái Nguyên", "Sông Công", "Phổ Yên", "Phú Bình"],
    marketContext: "Thái Nguyên có Samsung SDI (pin điện thoại) và Samsung Display tại Yên Bình, thu hút hàng chục nghìn lao động kỹ thuật cao. Đại học Thái Nguyên với hàng vạn sinh viên cũng là thị trường lớn cho máy bán hàng tự động tại ký túc xá và khuôn viên trường.",
    lockerContext: "Ký túc xá Đại học Thái Nguyên và khu nhà ở Samsung tại Yên Bình là địa điểm tiềm năng cho tủ locker thông minh.",
    deliveryNote: "Lắp đặt tại Thái Nguyên trong 2–3 ngày làm việc từ Hà Nội.",
  },
  {
    slug: "lang-son",
    name: "Lạng Sơn",
    region: "north",
    demandLevel: "low",
    population: "0,8 triệu",
    keyIndustries: ["thương mại biên giới", "nông lâm sản", "du lịch"],
    industrialZones: ["KCN Đồng Bành", "Cửa khẩu Hữu Nghị"],
    notableAreas: ["TP. Lạng Sơn", "Đồng Đăng", "Hữu Nghị"],
    marketContext: "Lạng Sơn là cửa ngõ thương mại biên giới lớn nhất phía Bắc với Trung Quốc. Luồng hàng hóa xuất nhập khẩu lớn qua cửa khẩu Hữu Nghị tạo nhu cầu cho máy bán hàng tự động tại khu logistic và trung tâm thương mại Đồng Đăng.",
    lockerContext: "Khu trung chuyển hàng hóa và nhà kho logistics tại Đồng Đăng là địa điểm tiềm năng cho tủ locker bảo quản hàng nhỏ.",
    deliveryNote: "Lắp đặt tại Lạng Sơn trong 3–4 ngày làm việc.",
  },
  {
    slug: "bac-giang",
    name: "Bắc Giang",
    region: "north",
    demandLevel: "high",
    population: "1,9 triệu",
    keyIndustries: ["điện tử - công nghệ cao", "may mặc", "nông sản"],
    industrialZones: ["KCN Vân Trung", "KCN Đình Trám", "KCN Song Khê - Nội Hoàng", "KCN Quang Châu", "KCN Hòa Phú"],
    notableAreas: ["TP. Bắc Giang", "Việt Yên", "Lạng Giang", "Yên Dũng"],
    marketContext: "Bắc Giang trở thành cứ điểm sản xuất điện tử lớn thứ ba miền Bắc sau Bắc Ninh và Thái Nguyên, với Foxconn, Luxshare-ICT, Goertek. Hàng trăm nghìn công nhân làm việc 3 ca là thị trường lớn cho máy bán hàng tự động tại các KCN Vân Trung và Quang Châu.",
    lockerContext: "Khu nhà ở công nhân quy mô lớn tại Việt Yên và Lạng Giang là cơ hội lớn cho tủ locker thông minh quản lý bưu phẩm.",
    deliveryNote: "Lắp đặt tại Bắc Giang trong 1–2 ngày làm việc.",
  },
  {
    slug: "phu-tho",
    name: "Phú Thọ",
    region: "north",
    demandLevel: "low",
    population: "1,5 triệu",
    keyIndustries: ["giấy - bao bì", "hóa chất", "chế biến nông lâm sản"],
    industrialZones: ["KCN Thụy Vân", "KCN Trung Hà", "KCN Phú Hà"],
    notableAreas: ["Việt Trì", "Phú Thọ", "Lâm Thao"],
    marketContext: "Phú Thọ có Khu di tích Đền Hùng thu hút triệu lượt khách hành hương mỗi năm dịp giỗ Tổ. Nhu cầu máy bán hàng tự động tại khu du lịch tâm linh và KCN Thụy Vân đang tăng trưởng ổn định.",
    lockerContext: "Các khu du lịch tâm linh và nhà nghỉ tại Đền Hùng có nhu cầu lưu trữ đồ cho khách hành hương theo mùa lễ hội.",
    deliveryNote: "Lắp đặt tại Phú Thọ trong 2–3 ngày làm việc từ Hà Nội.",
  },
  {
    slug: "hoa-binh",
    name: "Hòa Bình",
    region: "north",
    demandLevel: "low",
    population: "0,9 triệu",
    keyIndustries: ["thủy điện", "du lịch sinh thái", "nông lâm nghiệp"],
    industrialZones: ["KCN Lương Sơn", "KCN Nhuận Trạch"],
    notableAreas: ["TP. Hòa Bình", "Lương Sơn", "Mai Châu"],
    marketContext: "Hòa Bình nổi tiếng với Hồ Hòa Bình và các khu du lịch Mai Châu, Thung Nai thu hút khách cuối tuần từ Hà Nội. KCN Lương Sơn ngay cửa ngõ Hà Nội cũng đang phát triển các nhà máy sản xuất nhỏ và vừa.",
    lockerContext: "Resort và homestay tại Mai Châu, Thung Nai có nhu cầu tủ locker lưu trữ hành lý cho khách du lịch ngắn ngày.",
    deliveryNote: "Lắp đặt tại Hòa Bình trong 1–2 ngày làm việc từ Hà Nội.",
  },
  {
    slug: "son-la",
    name: "Sơn La",
    region: "north",
    demandLevel: "low",
    population: "1,3 triệu",
    keyIndustries: ["nông nghiệp - cây ăn quả", "thủy điện", "du lịch"],
    industrialZones: ["KCN Mai Sơn"],
    notableAreas: ["TP. Sơn La", "Mai Sơn", "Mộc Châu"],
    marketContext: "Sơn La nổi tiếng với vùng cây ăn quả lớn nhất Tây Bắc (xoài, nhãn, mận). Khu du lịch Mộc Châu đang phát triển thành điểm nghỉ dưỡng cuối tuần phổ biến. Nhu cầu máy bán hàng tự động tại Mộc Châu và bệnh viện tỉnh đang được quan tâm.",
    lockerContext: "Khu du lịch Mộc Châu với các resort và farmstay đang phát triển có nhu cầu thiết bị tự phục vụ.",
    deliveryNote: "Lắp đặt tại Sơn La trong 5–7 ngày làm việc. Vận chuyển đặc biệt cho vùng miền núi.",
  },
  {
    slug: "lao-cai",
    name: "Lào Cai",
    region: "north",
    demandLevel: "low",
    population: "0,8 triệu",
    keyIndustries: ["du lịch - Sa Pa", "khai khoáng", "thương mại biên giới"],
    industrialZones: ["KCN Đông Phố Mới", "KCN Tằng Loỏng"],
    notableAreas: ["TP. Lào Cai", "Sa Pa", "Bắc Hà"],
    marketContext: "Sa Pa là điểm du lịch quốc tế nổi tiếng với lượng khách lớn quanh năm. Nhu cầu máy bán hàng tự động tại các khách sạn lớn, khu cáp treo Fansipan và trung tâm thị trấn Sa Pa rất thực tế, đặc biệt trong mùa cao điểm thu đông.",
    lockerContext: "Khách sạn và resort tại Sa Pa có nhu cầu tủ locker self-check-in và lưu trữ hành lý cho khách du lịch.",
    deliveryNote: "Lắp đặt tại Lào Cai trong 5–7 ngày làm việc.",
  },
  {
    slug: "dien-bien",
    name: "Điện Biên",
    region: "north",
    demandLevel: "low",
    population: "0,6 triệu",
    keyIndustries: ["du lịch lịch sử", "nông nghiệp", "thương mại biên giới"],
    industrialZones: [],
    notableAreas: ["TP. Điện Biên Phủ", "Mường Ảnh"],
    marketContext: "Điện Biên Phủ là điểm du lịch lịch sử với di tích chiến thắng Điện Biên Phủ. Nhu cầu máy bán hàng tự động khiêm tốn nhưng có tiềm năng tại sân bay Điện Biên và khu du lịch lịch sử phục vụ khách từ xa.",
    lockerContext: "Sân bay Điện Biên Phủ là địa điểm tiềm năng nhỏ cho máy bán hàng tự động phục vụ hành khách.",
    deliveryNote: "Lắp đặt tại Điện Biên theo yêu cầu, thời gian 7–10 ngày làm việc.",
  },
  {
    slug: "lai-chau",
    name: "Lai Châu",
    region: "north",
    demandLevel: "low",
    population: "0,5 triệu",
    keyIndustries: ["thủy điện", "khai khoáng", "nông lâm nghiệp"],
    industrialZones: [],
    notableAreas: ["TP. Lai Châu", "Phong Thổ", "Sìn Hồ"],
    marketContext: "Lai Châu là tỉnh biên giới Tây Bắc còn nhiều khó khăn. Nhu cầu thiết bị tự động hóa đang ở giai đoạn rất sơ khai. Tiềm năng dài hạn gắn liền với phát triển hạ tầng du lịch khám phá.",
    lockerContext: "Hiện tại nhu cầu tủ locker thông minh tại Lai Châu rất hạn chế, phù hợp hơn trong giai đoạn 2028–2030 khi hạ tầng phát triển.",
    deliveryNote: "Lắp đặt tại Lai Châu theo yêu cầu đặc biệt, thời gian 10–14 ngày.",
  },
  {
    slug: "ha-giang",
    name: "Hà Giang",
    region: "north",
    demandLevel: "low",
    population: "0,9 triệu",
    keyIndustries: ["du lịch khám phá", "nông nghiệp", "khai khoáng"],
    industrialZones: [],
    notableAreas: ["TP. Hà Giang", "Đồng Văn", "Mèo Vạc", "Hoàng Su Phì"],
    marketContext: "Hà Giang nổi tiếng với Cao nguyên đá Đồng Văn và mùa hoa tam giác mạch thu hút du khách trẻ. Nhu cầu máy bán hàng tự động đang hình thành tại các homestay và điểm dịch vụ dọc tour Hà Giang Loop.",
    lockerContext: "Homestay tại Đồng Văn, Mèo Vạc có thể hưởng lợi từ tủ locker mini cho khách phượt lưu trữ hành lý.",
    deliveryNote: "Lắp đặt tại Hà Giang theo yêu cầu đặc biệt, 10–14 ngày.",
  },
  {
    slug: "cao-bang",
    name: "Cao Bằng",
    region: "north",
    demandLevel: "low",
    population: "0,5 triệu",
    keyIndustries: ["khai khoáng", "nông lâm nghiệp", "du lịch"],
    industrialZones: [],
    notableAreas: ["TP. Cao Bằng", "Trùng Khánh", "Hà Quảng"],
    marketContext: "Cao Bằng có thác Bản Giốc – điểm du lịch thiên nhiên nổi tiếng. Nhu cầu máy bán hàng tự động còn rất hạn chế, phù hợp nhất tại sân bay Cao Bằng và khu du lịch Bản Giốc trong tương lai.",
    lockerContext: "Tiềm năng tủ locker rất hạn chế tại giai đoạn hiện tại.",
    deliveryNote: "Lắp đặt tại Cao Bằng theo yêu cầu đặc biệt.",
  },
  {
    slug: "bac-kan",
    name: "Bắc Kạn",
    region: "north",
    demandLevel: "low",
    population: "0,3 triệu",
    keyIndustries: ["khai khoáng", "nông lâm nghiệp", "du lịch hồ Ba Bể"],
    industrialZones: [],
    notableAreas: ["TP. Bắc Kạn", "Hồ Ba Bể"],
    marketContext: "Bắc Kạn là tỉnh nhỏ nhất Việt Nam về dân số. Vườn quốc gia Ba Bể là điểm du lịch sinh thái đang phát triển. Nhu cầu máy bán hàng tự động rất hạn chế.",
    lockerContext: "Tiềm năng tủ locker rất hạn chế ở giai đoạn hiện tại.",
    deliveryNote: "Lắp đặt tại Bắc Kạn theo yêu cầu đặc biệt.",
  },
  {
    slug: "tuyen-quang",
    name: "Tuyên Quang",
    region: "north",
    demandLevel: "low",
    population: "0,8 triệu",
    keyIndustries: ["giấy - bao bì", "thủy điện", "nông lâm nghiệp"],
    industrialZones: ["KCN Long Bình An"],
    notableAreas: ["TP. Tuyên Quang", "Sơn Dương", "Chiêm Hóa"],
    marketContext: "Tuyên Quang có nhà máy giấy và chế biến gỗ lớn, tạo nhu cầu nhỏ cho máy bán hàng tại khu nhà ở công nhân. Lễ hội Trung Thu Tuyên Quang nổi tiếng thu hút du khách trong và ngoài tỉnh.",
    lockerContext: "Nhu cầu tủ locker còn hạn chế, phù hợp với giai đoạn phát triển tiếp theo.",
    deliveryNote: "Lắp đặt tại Tuyên Quang trong 3–4 ngày làm việc từ Hà Nội.",
  },
  {
    slug: "yen-bai",
    name: "Yên Bái",
    region: "north",
    demandLevel: "low",
    population: "0,8 triệu",
    keyIndustries: ["khai khoáng (đá quý)", "nông lâm nghiệp", "du lịch Mù Cang Chải"],
    industrialZones: ["KCN Phía Nam"],
    notableAreas: ["TP. Yên Bái", "Nghĩa Lộ", "Mù Cang Chải"],
    marketContext: "Mù Cang Chải với ruộng bậc thang đã được xếp hạng danh lam thắng cảnh quốc gia, thu hút du khách mùa lúa chín. Nhu cầu máy bán hàng tự động còn rất sơ khai nhưng có tiềm năng cùng phát triển du lịch.",
    lockerContext: "Điểm du lịch Mù Cang Chải có thể có nhu cầu nhỏ cho thiết bị tự phục vụ.",
    deliveryNote: "Lắp đặt tại Yên Bái trong 4–5 ngày làm việc.",
  },
  {
    slug: "ha-nam",
    name: "Hà Nam",
    region: "north",
    demandLevel: "medium",
    population: "0,9 triệu",
    keyIndustries: ["sản xuất công nghiệp", "vật liệu xây dựng", "chế biến nông sản"],
    industrialZones: ["KCN Đồng Văn I-III", "KCN Châu Sơn", "KCN Hòa Mạc"],
    notableAreas: ["Phủ Lý", "Đồng Văn", "Duy Tiên"],
    marketContext: "Hà Nam nằm ngay phía Nam Hà Nội trên trục quốc lộ 1A, đang là điểm đến của nhiều doanh nghiệp FDI Hàn Quốc và Nhật Bản chuyển từ Hà Nội. KCN Đồng Văn đang lấp đầy nhanh, tạo nhu cầu thiết thực cho máy bán hàng tự động.",
    lockerContext: "Khu nhà ở công nhân tại các KCN Đồng Văn và Châu Sơn đang phát triển.",
    deliveryNote: "Lắp đặt tại Hà Nam trong 1–2 ngày làm việc từ Hà Nội.",
  },
  {
    slug: "nam-dinh",
    name: "Nam Định",
    region: "north",
    demandLevel: "low",
    population: "1,9 triệu",
    keyIndustries: ["dệt may", "thực phẩm", "cơ khí"],
    industrialZones: ["KCN Hòa Xá", "KCN Mỹ Trung"],
    notableAreas: ["TP. Nam Định", "Xuân Trường", "Hải Hậu"],
    marketContext: "Nam Định nổi tiếng với ngành dệt may và lễ hội phủ Giầy. KCN Hòa Xá tập trung nhiều nhà máy dệt may và thực phẩm với đông đảo lao động. Bệnh viện Đa khoa Nam Định và các trường đại học cũng là thị trường tiềm năng.",
    lockerContext: "Nhu cầu tủ locker tại chung cư mới tại TP. Nam Định đang hình thành.",
    deliveryNote: "Lắp đặt tại Nam Định trong 2–3 ngày làm việc.",
  },
  {
    slug: "thai-binh",
    name: "Thái Bình",
    region: "north",
    demandLevel: "low",
    population: "1,9 triệu",
    keyIndustries: ["dệt may", "nông nghiệp lúa nước", "chế biến thủy sản"],
    industrialZones: ["KCN Phúc Khánh", "KCN Tiền Hải", "KCN Gia Lễ"],
    notableAreas: ["TP. Thái Bình", "Tiền Hải", "Đông Hưng"],
    marketContext: "Thái Bình là tỉnh nông nghiệp và dệt may lớn vùng đồng bằng sông Hồng. KCN Tiền Hải đang thu hút đầu tư mới. Bệnh viện Đa khoa Thái Bình phục vụ dân số lớn và là địa điểm tiềm năng cho máy bán hàng tự động.",
    lockerContext: "Nhu cầu tủ locker còn khiêm tốn, gắn với các dự án nhà ở đô thị mới tại TP. Thái Bình.",
    deliveryNote: "Lắp đặt tại Thái Bình trong 2–3 ngày làm việc.",
  },
  {
    slug: "ninh-binh",
    name: "Ninh Bình",
    region: "north",
    demandLevel: "medium",
    population: "1,0 triệu",
    keyIndustries: ["du lịch - di sản", "sản xuất ô tô (Hyundai Thành Công)", "vật liệu xây dựng"],
    industrialZones: ["KCN Gián Khẩu", "KCN Khánh Phú", "KCN Phúc Sơn"],
    notableAreas: ["Ninh Bình", "Hoa Lư", "Tam Cốc - Tràng An", "Tam Điệp"],
    marketContext: "Ninh Bình nổi bật với Quần thể danh thắng Tràng An (UNESCO) và nhà máy lắp ráp ô tô Hyundai Thành Công. Lưu lượng du khách lớn tại khu du lịch và hàng nghìn công nhân nhà máy ô tô tạo hai thị trường song song cho máy bán hàng tự động.",
    lockerContext: "Resort và khách sạn tại Tràng An, Tam Cốc có nhu cầu tủ locker lưu trữ hành lý cho khách du lịch.",
    deliveryNote: "Lắp đặt tại Ninh Bình trong 2–3 ngày làm việc từ Hà Nội.",
  },
  {
    slug: "quang-binh",
    name: "Quảng Bình",
    region: "central",
    demandLevel: "low",
    population: "0,9 triệu",
    keyIndustries: ["du lịch Phong Nha", "nông lâm ngư nghiệp", "khai khoáng"],
    industrialZones: ["KCN Tây Bắc Đồng Hới", "KCN Hòn La"],
    notableAreas: ["Đồng Hới", "Phong Nha", "Hòn La"],
    marketContext: "Quảng Bình với Hang Sơn Đoòng và hệ thống hang động Phong Nha là điểm du lịch khám phá nổi tiếng quốc tế. Nhu cầu máy bán hàng tự động tại khu du lịch Phong Nha và sân bay Đồng Hới đang hình thành.",
    lockerContext: "Resort và khu du lịch Phong Nha có nhu cầu tủ locker lưu giữ đồ dùng của du khách trước khi vào hang.",
    deliveryNote: "Lắp đặt tại Quảng Bình trong 4–5 ngày làm việc.",
  },
  {
    slug: "quang-tri",
    name: "Quảng Trị",
    region: "central",
    demandLevel: "low",
    population: "0,6 triệu",
    keyIndustries: ["du lịch lịch sử", "nông lâm nghiệp", "điện gió"],
    industrialZones: ["KKT Đông Nam Quảng Trị"],
    notableAreas: ["Đông Hà", "Khe Sanh", "Cửa Việt"],
    marketContext: "Quảng Trị là tỉnh có nhiều di tích lịch sử chiến tranh thu hút khách du lịch lịch sử. KKT Đông Nam với cảng biển Mỹ Thủy đang trong giai đoạn xây dựng. Nhu cầu máy bán hàng tự động hiện ở mức khiêm tốn.",
    lockerContext: "Tiềm năng tủ locker gắn liền với phát triển KKT Đông Nam trong giai đoạn tiếp theo.",
    deliveryNote: "Lắp đặt tại Quảng Trị trong 3–4 ngày làm việc.",
  },
  {
    slug: "kon-tum",
    name: "Kon Tum",
    region: "central",
    demandLevel: "low",
    population: "0,6 triệu",
    keyIndustries: ["nông lâm nghiệp", "du lịch sinh thái", "thủy điện"],
    industrialZones: ["KCN Hòa Bình"],
    notableAreas: ["TP. Kon Tum", "Đăk Hà"],
    marketContext: "Kon Tum là tỉnh Tây Nguyên với diện tích rừng lớn và đồng bào dân tộc thiểu số đông. Nhu cầu máy bán hàng tự động rất hạn chế, chủ yếu tập trung tại TP. Kon Tum và bệnh viện tỉnh.",
    lockerContext: "Nhu cầu tủ locker rất hạn chế ở giai đoạn hiện tại.",
    deliveryNote: "Lắp đặt tại Kon Tum theo yêu cầu, 5–7 ngày làm việc.",
  },
  {
    slug: "gia-lai",
    name: "Gia Lai",
    region: "central",
    demandLevel: "low",
    population: "1,6 triệu",
    keyIndustries: ["nông nghiệp (cà phê, cao su)", "thủy điện", "chế biến nông sản"],
    industrialZones: ["KCN Trà Đa", "KCN Ia Sao"],
    notableAreas: ["Pleiku", "An Khê", "Ayun Pa"],
    marketContext: "Gia Lai là thủ phủ cà phê và cao su Tây Nguyên. TP. Pleiku với bệnh viện vùng, trường đại học và các doanh nghiệp chế biến nông sản tạo nhu cầu ổn định cho máy bán hàng tự động phục vụ cán bộ và người lao động.",
    lockerContext: "Khu đô thị mới tại Pleiku đang phát triển, nhu cầu tủ locker đang hình thành.",
    deliveryNote: "Lắp đặt tại Gia Lai trong 5–6 ngày làm việc.",
  },
  {
    slug: "dak-lak",
    name: "Đắk Lắk",
    region: "central",
    demandLevel: "medium",
    population: "1,9 triệu",
    keyIndustries: ["cà phê - nông nghiệp", "chế biến nông sản", "du lịch sinh thái"],
    industrialZones: ["KCN Hòa Phú", "KCN Tâm Thắng"],
    notableAreas: ["Buôn Ma Thuột", "Buôn Hồ", "Krông Búk"],
    marketContext: "Buôn Ma Thuột là thủ đô cà phê Việt Nam với nhiều nhà máy chế biến và thương lái lớn. Lực lượng công nhân và nhân viên văn phòng ngành cà phê, cùng sinh viên các trường đại học tại đây, tạo nhu cầu thiết thực cho máy bán hàng tự động.",
    lockerContext: "Chung cư và khu đô thị mới tại Buôn Ma Thuột có nhu cầu tủ locker đang hình thành.",
    deliveryNote: "Lắp đặt tại Đắk Lắk trong 5–6 ngày làm việc.",
  },
  {
    slug: "dak-nong",
    name: "Đắk Nông",
    region: "central",
    demandLevel: "low",
    population: "0,7 triệu",
    keyIndustries: ["alumin - khai khoáng", "nông nghiệp", "thủy điện"],
    industrialZones: ["KCN Nhân Cơ", "KCN Tâm Thắng"],
    notableAreas: ["Gia Nghĩa", "Đắk Song", "Đắk Mil"],
    marketContext: "Đắk Nông có nhà máy alumin Nhân Cơ lớn của TKV, thu hút lao động kỹ thuật. Công viên địa chất Global Geopark Đắk Nông đang phát triển du lịch. Nhu cầu máy bán hàng tự động còn rất hạn chế.",
    lockerContext: "Nhu cầu tủ locker rất hạn chế ở giai đoạn hiện tại.",
    deliveryNote: "Lắp đặt tại Đắk Nông trong 6–7 ngày làm việc.",
  },
  {
    slug: "ninh-thuan",
    name: "Ninh Thuận",
    region: "central",
    demandLevel: "low",
    population: "0,6 triệu",
    keyIndustries: ["du lịch biển", "điện gió - điện mặt trời", "nho - cừu"],
    industrialZones: ["KCN Thành Hải"],
    notableAreas: ["Phan Rang - Tháp Chàm", "Ninh Hải"],
    marketContext: "Ninh Thuận nổi tiếng với nho, cừu và tốc độ phát triển năng lượng tái tạo nhanh nhất Việt Nam. Khu du lịch biển Ninh Chữ và Vĩnh Hy đang thu hút đầu tư. Nhu cầu máy bán hàng tự động còn khiêm tốn.",
    lockerContext: "Resort biển tại Ninh Chữ, Bình Tiên có nhu cầu nhỏ cho tủ locker phục vụ khách.",
    deliveryNote: "Lắp đặt tại Ninh Thuận trong 4–5 ngày làm việc.",
  },
  {
    slug: "binh-thuan",
    name: "Bình Thuận",
    region: "central",
    demandLevel: "medium",
    population: "1,3 triệu",
    keyIndustries: ["du lịch Mũi Né", "đánh bắt thủy sản", "thanh long", "điện gió"],
    industrialZones: ["KCN Phan Thiết", "KCN Hàm Kiệm"],
    notableAreas: ["Phan Thiết", "Mũi Né", "La Gi"],
    marketContext: "Mũi Né – Phan Thiết là điểm du lịch biển nổi tiếng thứ ba cả nước với resort 5 sao, khu vui chơi Vinpearl và làng chài. Nhu cầu máy bán hàng tự động tại khu resort, khách sạn và dịch vụ du lịch tự phục vụ đang tăng theo lượng khách quốc tế.",
    lockerContext: "Resort và condotel tại Mũi Né có nhu cầu tủ locker lưu trữ hành lý và dụng cụ thể thao nước.",
    deliveryNote: "Lắp đặt tại Bình Thuận trong 3–4 ngày làm việc từ TP.HCM.",
  },
  {
    slug: "ba-ria-vung-tau",
    name: "Bà Rịa - Vũng Tàu",
    region: "south",
    demandLevel: "high",
    population: "1,2 triệu",
    keyIndustries: ["dầu khí - hóa dầu", "cảng biển - logistics", "du lịch biển", "sản xuất công nghiệp"],
    industrialZones: ["KCN Đông Xuyên", "KCN Phú Mỹ 1-3", "KCN Mỹ Xuân A-B", "KCN Châu Đức", "KCN Long Hương"],
    notableAreas: ["Vũng Tàu", "Bà Rịa", "Phú Mỹ", "Long Điền"],
    marketContext: "BRVT là trung tâm dầu khí Việt Nam với PetroVietnam và hàng chục công ty dầu khí quốc tế. Cụm cảng Cái Mép - Thị Vải là cảng container hiện đại nhất Việt Nam. Cùng với du lịch biển Vũng Tàu phục vụ dân TP.HCM cuối tuần, đây là thị trường có sức mua cao và nhu cầu đa dạng cho máy bán hàng tự động.",
    lockerContext: "Resort, khách sạn tại Vũng Tàu và khu nhà ở kỹ sư dầu khí tại Phú Mỹ có nhu cầu tủ locker thông minh cao.",
    deliveryNote: "Lắp đặt tại BRVT trong 1–2 ngày làm việc từ TP.HCM.",
  },
  {
    slug: "tay-ninh",
    name: "Tây Ninh",
    region: "south",
    demandLevel: "medium",
    population: "1,2 triệu",
    keyIndustries: ["sản xuất công nghiệp", "du lịch tâm linh Núi Bà", "mì - nông sản"],
    industrialZones: ["KCN Trảng Bàng", "KCN Phước Đông", "KCN Linh Trung III"],
    notableAreas: ["Tây Ninh", "Trảng Bàng", "Gò Dầu"],
    marketContext: "Tây Ninh có KCN Trảng Bàng và Phước Đông tiếp giáp TP.HCM với nhiều nhà máy dệt may, giày dép. Núi Bà Đen là điểm du lịch tâm linh hàng đầu miền Nam thu hút hàng triệu khách hành hương. Cửa khẩu Mộc Bài cũng tạo nhu cầu thương mại biên giới.",
    lockerContext: "Khu nhà ở công nhân tại Trảng Bàng và khu du lịch Núi Bà Đen là địa điểm tiềm năng cho tủ locker.",
    deliveryNote: "Lắp đặt tại Tây Ninh trong 1–2 ngày làm việc từ TP.HCM.",
  },
  {
    slug: "binh-phuoc",
    name: "Bình Phước",
    region: "south",
    demandLevel: "medium",
    population: "1,1 triệu",
    keyIndustries: ["cao su - điều", "sản xuất công nghiệp", "gỗ nội thất"],
    industrialZones: ["KCN Đồng Xoài", "KCN Becamex Bình Phước", "KCN Minh Hưng - Hàn Quốc"],
    notableAreas: ["Đồng Xoài", "Chơn Thành", "Bình Long", "Phước Long"],
    marketContext: "Bình Phước đang phát triển nhanh với KCN Becamex thu hút đầu tư FDI Hàn Quốc và Đài Loan. Ngành cao su, điều và gỗ truyền thống cùng với làn sóng công nghiệp hóa tạo nhu cầu tăng trưởng cho máy bán hàng tự động.",
    lockerContext: "Khu nhà ở công nhân tại KCN Becamex và Minh Hưng đang phát triển nhanh.",
    deliveryNote: "Lắp đặt tại Bình Phước trong 2–3 ngày làm việc.",
  },
  {
    slug: "long-an",
    name: "Long An",
    region: "south",
    demandLevel: "medium",
    population: "1,8 triệu",
    keyIndustries: ["sản xuất công nghiệp", "nông nghiệp - lúa gạo", "logistics"],
    industrialZones: ["KCN Tân Đức", "KCN Long Hậu", "KCN Xuyên Á", "KCN Cầu Tràm", "KCN Thuận Đạo"],
    notableAreas: ["Tân An", "Bến Lức", "Đức Hòa", "Cần Giuộc"],
    marketContext: "Long An là tỉnh vệ tinh TP.HCM đang bùng nổ về công nghiệp. KCN Long Hậu, Tân Đức lấp đầy nhanh với các nhà máy FDI tại hành lang kinh tế TP.HCM - Cần Thơ. Hàng trăm nghìn công nhân là thị trường lớn cho máy bán hàng tự động.",
    lockerContext: "Khu nhà ở công nhân và khu dân cư mới ven TP.HCM tại Bến Lức, Cần Giuộc có nhu cầu tủ locker tăng nhanh.",
    deliveryNote: "Lắp đặt tại Long An trong 1–2 ngày làm việc từ TP.HCM.",
  },
  {
    slug: "tien-giang",
    name: "Tiền Giang",
    region: "south",
    demandLevel: "medium",
    population: "1,8 triệu",
    keyIndustries: ["chế biến trái cây", "thủy sản", "thương mại - dịch vụ"],
    industrialZones: ["KCN Tân Hương", "KCN Long Giang", "KCN Mỹ Tho"],
    notableAreas: ["Mỹ Tho", "Gò Công", "Cai Lậy", "Cái Bè"],
    marketContext: "Tiền Giang là cửa ngõ vào Đồng bằng sông Cửu Long, có Mỹ Tho là đô thị lớn và điểm du lịch sông nước nổi tiếng. KCN Long Giang quy mô lớn đang thu hút FDI. Bệnh viện Đa khoa Tiền Giang phục vụ dân số lớn vùng đồng bằng.",
    lockerContext: "Chung cư và khu đô thị mới tại Mỹ Tho có nhu cầu tủ locker đang hình thành.",
    deliveryNote: "Lắp đặt tại Tiền Giang trong 2–3 ngày làm việc từ TP.HCM.",
  },
  {
    slug: "ben-tre",
    name: "Bến Tre",
    region: "south",
    demandLevel: "low",
    population: "1,3 triệu",
    keyIndustries: ["dừa - chế biến nông sản", "thủy sản", "du lịch sông nước"],
    industrialZones: ["KCN Giao Long", "KCN An Hiệp"],
    notableAreas: ["Bến Tre", "Châu Thành", "Mỏ Cày"],
    marketContext: "Bến Tre là 'xứ dừa' với công nghiệp chế biến dừa lớn nhất Việt Nam. Du lịch sinh thái sông nước đang phát triển. Nhu cầu máy bán hàng tự động ở mức vừa phải tại TP. Bến Tre và khu công nghiệp.",
    lockerContext: "Nhu cầu tủ locker còn hạn chế, gắn với phát triển đô thị tại TP. Bến Tre.",
    deliveryNote: "Lắp đặt tại Bến Tre trong 2–3 ngày làm việc.",
  },
  {
    slug: "tra-vinh",
    name: "Trà Vinh",
    region: "south",
    demandLevel: "low",
    population: "1,1 triệu",
    keyIndustries: ["nông - thủy sản", "điện gió - điện mặt trời", "dệt may"],
    industrialZones: ["KCN Long Đức"],
    notableAreas: ["Trà Vinh", "Cầu Kè", "Tiểu Cần"],
    marketContext: "Trà Vinh đang phát triển KCN Long Đức và thu hút đầu tư điện gió ven biển. Trường Đại học Trà Vinh là trung tâm đào tạo vùng ĐBSCL. Nhu cầu máy bán hàng tự động còn hạn chế.",
    lockerContext: "Nhu cầu tủ locker rất hạn chế ở giai đoạn hiện tại.",
    deliveryNote: "Lắp đặt tại Trà Vinh trong 3–4 ngày làm việc.",
  },
  {
    slug: "vinh-long",
    name: "Vĩnh Long",
    region: "south",
    demandLevel: "low",
    population: "1,1 triệu",
    keyIndustries: ["nông nghiệp - gạo", "du lịch sông nước", "chế biến thực phẩm"],
    industrialZones: ["KCN Hòa Phú", "KCN Bình Minh"],
    notableAreas: ["Vĩnh Long", "Bình Minh", "Long Hồ"],
    marketContext: "Vĩnh Long nổi tiếng với du lịch vườn cù lao, nơi khách du lịch trải nghiệm cuộc sống miền Tây. KCN Bình Minh và Hòa Phú đang thu hút đầu tư sản xuất gạch men và thực phẩm. Nhu cầu máy bán hàng tự động ở mức khiêm tốn.",
    lockerContext: "Nhu cầu tủ locker gắn với phát triển đô thị tại TP. Vĩnh Long.",
    deliveryNote: "Lắp đặt tại Vĩnh Long trong 3–4 ngày làm việc.",
  },
  {
    slug: "dong-thap",
    name: "Đồng Tháp",
    region: "south",
    demandLevel: "low",
    population: "1,6 triệu",
    keyIndustries: ["lúa gạo - nông nghiệp", "thủy sản (cá tra)", "du lịch Tháp Mười"],
    industrialZones: ["KCN Sa Đéc", "KCN Trần Quốc Toản"],
    notableAreas: ["Cao Lãnh", "Sa Đéc", "Hồng Ngự"],
    marketContext: "Đồng Tháp là vựa lúa và xuất khẩu cá tra lớn của cả nước. Sa Đéc nổi tiếng với làng hoa và du lịch. Nhu cầu máy bán hàng tự động tập trung tại bệnh viện và cơ quan hành chính TP. Cao Lãnh và Sa Đéc.",
    lockerContext: "Nhu cầu tủ locker còn hạn chế ở giai đoạn hiện tại.",
    deliveryNote: "Lắp đặt tại Đồng Tháp trong 4–5 ngày làm việc.",
  },
  {
    slug: "an-giang",
    name: "An Giang",
    region: "south",
    demandLevel: "low",
    population: "1,9 triệu",
    keyIndustries: ["thương mại biên giới", "thủy sản", "du lịch Núi Sam"],
    industrialZones: ["KCN Bình Long", "KCN Mỹ Quý"],
    notableAreas: ["Long Xuyên", "Châu Đốc", "An Phú"],
    marketContext: "An Giang là tỉnh đông dân nhất ĐBSCL với cửa khẩu Tịnh Biên và Vĩnh Xương giao thương với Campuchia. Núi Sam - Châu Đốc là điểm hành hương lớn nhất vùng. Nhu cầu máy bán hàng tự động tại chợ biên giới và khu du lịch tâm linh đang hình thành.",
    lockerContext: "Khu hành hương Núi Sam và chợ biên giới có nhu cầu nhỏ cho máy bán hàng tự động.",
    deliveryNote: "Lắp đặt tại An Giang trong 4–5 ngày làm việc.",
  },
  {
    slug: "kien-giang",
    name: "Kiên Giang",
    region: "south",
    demandLevel: "medium",
    population: "1,8 triệu",
    keyIndustries: ["du lịch Phú Quốc", "thủy sản", "chế biến nông sản"],
    industrialZones: ["KCN Thạnh Lộc", "KCN Kiên Lương"],
    notableAreas: ["Rạch Giá", "Phú Quốc", "Hà Tiên"],
    marketContext: "Phú Quốc — 'đảo ngọc' với sân bay quốc tế, casino Vinpearl và chuỗi resort 5 sao — là điểm du lịch tăng trưởng nóng nhất Việt Nam. Nhu cầu máy bán hàng tự động và tủ locker thông minh tại Phú Quốc rất cao và tăng liên tục theo lượng khách quốc tế.",
    lockerContext: "Resort, casino và khu nghỉ dưỡng tại Phú Quốc có nhu cầu tủ locker thông minh cho lưu trữ hành lý và nhận hàng của khách lưu trú.",
    deliveryNote: "Lắp đặt tại Kiên Giang trong 3–4 ngày (cần vận chuyển đặc biệt sang đảo Phú Quốc).",
  },
  {
    slug: "hau-giang",
    name: "Hậu Giang",
    region: "south",
    demandLevel: "low",
    population: "0,8 triệu",
    keyIndustries: ["nông nghiệp - mía đường", "thủy sản", "chế biến nông sản"],
    industrialZones: ["KCN Sông Hậu", "KCN Tân Phú Thạnh"],
    notableAreas: ["Vị Thanh", "Ngã Bảy"],
    marketContext: "Hậu Giang là tỉnh mới tách từ Cần Thơ đang trong giai đoạn phát triển. KCN Sông Hậu đang thu hút đầu tư sản xuất. Nhu cầu máy bán hàng tự động còn hạn chế.",
    lockerContext: "Nhu cầu tủ locker còn rất hạn chế ở giai đoạn hiện tại.",
    deliveryNote: "Lắp đặt tại Hậu Giang trong 3–4 ngày làm việc từ Cần Thơ.",
  },
  {
    slug: "soc-trang",
    name: "Sóc Trăng",
    region: "south",
    demandLevel: "low",
    population: "1,2 triệu",
    keyIndustries: ["thủy sản (tôm)", "nông nghiệp", "dệt may"],
    industrialZones: ["KCN An Nghiệp", "KCN Trần Đề"],
    notableAreas: ["TP. Sóc Trăng", "Ngã Năm", "Vĩnh Châu"],
    marketContext: "Sóc Trăng là tỉnh xuất khẩu tôm lớn nhất đồng bằng. KCN An Nghiệp và Trần Đề đang thu hút đầu tư chế biến thủy sản. Nhu cầu máy bán hàng tự động còn hạn chế.",
    lockerContext: "Nhu cầu tủ locker rất hạn chế ở giai đoạn hiện tại.",
    deliveryNote: "Lắp đặt tại Sóc Trăng trong 4–5 ngày làm việc.",
  },
  {
    slug: "bac-lieu",
    name: "Bạc Liêu",
    region: "south",
    demandLevel: "low",
    population: "0,9 triệu",
    keyIndustries: ["thủy sản", "điện gió", "nông nghiệp"],
    industrialZones: ["KCN Láng Trâm"],
    notableAreas: ["Bạc Liêu", "Giá Rai", "Vĩnh Lợi"],
    marketContext: "Bạc Liêu nổi tiếng với điện gió ven biển và di sản nhạc cải lương. Nhu cầu máy bán hàng tự động còn rất hạn chế, tập trung tại bệnh viện và cơ quan hành chính TP. Bạc Liêu.",
    lockerContext: "Nhu cầu tủ locker rất hạn chế ở giai đoạn hiện tại.",
    deliveryNote: "Lắp đặt tại Bạc Liêu trong 5–6 ngày làm việc.",
  },
  {
    slug: "ca-mau",
    name: "Cà Mau",
    region: "south",
    demandLevel: "low",
    population: "1,2 triệu",
    keyIndustries: ["tôm - thủy sản xuất khẩu", "khí đốt - điện", "rừng ngập mặn"],
    industrialZones: ["KCN Khánh An"],
    notableAreas: ["Cà Mau", "Năm Căn", "Đất Mũi"],
    marketContext: "Cà Mau là điểm cực Nam của Tổ quốc với vườn quốc gia U Minh Hạ và Đất Mũi. Xuất khẩu tôm đông lạnh lớn nhất cả nước. Nhu cầu máy bán hàng tự động tập trung tại TP. Cà Mau và bệnh viện tỉnh.",
    lockerContext: "Nhu cầu tủ locker rất hạn chế, tiềm năng phát triển dài hạn.",
    deliveryNote: "Lắp đặt tại Cà Mau trong 6–7 ngày làm việc.",
  },
  {
    slug: "phu-yen",
    name: "Phú Yên",
    region: "central",
    demandLevel: "low",
    population: "1,0 triệu",
    keyIndustries: ["du lịch biển", "thủy sản", "nông lâm nghiệp"],
    industrialZones: ["KCN Hòa Hiệp Nam", "KCN Đông Bắc Sông Cầu"],
    notableAreas: ["Tuy Hòa", "Sông Cầu", "Đông Hòa"],
    marketContext: "Phú Yên đang nổi lên là điểm đến du lịch mới với Gành Đá Đĩa, Mũi Điện và bãi Xép. Nhu cầu máy bán hàng tự động tại khu du lịch và bệnh viện tỉnh đang hình thành theo tốc độ phát triển du lịch.",
    lockerContext: "Khu resort mới tại Sông Cầu và ven biển Phú Yên có nhu cầu nhỏ cho tủ locker phục vụ khách lưu trú.",
    deliveryNote: "Lắp đặt tại Phú Yên trong 4–5 ngày làm việc.",
  },
  {
    slug: "quang-ngai",
    name: "Quảng Ngãi",
    region: "central",
    demandLevel: "medium",
    population: "1,4 triệu",
    keyIndustries: ["lọc dầu Dung Quất", "thép Hòa Phát", "đóng tàu", "nông lâm nghiệp"],
    industrialZones: ["KKT Dung Quất", "KCN VSIP Quảng Ngãi", "KCN Tịnh Phong"],
    notableAreas: ["Quảng Ngãi", "Dung Quất", "Đức Phổ"],
    marketContext: "Quảng Ngãi có KKT Dung Quất — nơi đặt Lọc dầu Bình Sơn và Thép Hòa Phát Dung Quất lớn nhất miền Trung. Hàng chục nghìn kỹ sư và công nhân tại đây là thị trường có thu nhập cao và nhu cầu tiêu dùng tiện lợi rõ ràng.",
    lockerContext: "Khu nhà ở kỹ sư và công nhân tại Dung Quất là địa điểm tiềm năng cho tủ locker thông minh.",
    deliveryNote: "Lắp đặt tại Quảng Ngãi trong 3–4 ngày làm việc.",
  },
];

export function getProvince(slug: string): Province | undefined {
  return PROVINCES.find((p) => p.slug === slug);
}

export function getProvincesByRegion(region: Province["region"]): Province[] {
  return PROVINCES.filter((p) => p.region === region);
}

export function getHighDemandProvinces(): Province[] {
  return PROVINCES.filter((p) => p.demandLevel === "high");
}
